name: ntopng
version: "0.1.0"
slug: ntopng
description: The SoHo FOSS & FREE ntopng with netflow collector
url: "https://github.com/litinoveweedle/hassio-addons/tree/main/ntopng"
image: "ghcr.io/litinoveweedle/hassio-addon-ntopng-{arch}"
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: "mdi:help-network-outline"
homeassistant: 2023.7.2
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
services:
  - mysql:want
  # - influxdb:want
map:
  - ssl
ports:
  80/tcp: null
  2055/udp: 2055
ports_description:
  80/tcp: ntopng web interface (Not required for Ingress)
  2055/udp: NetFlow2NG NetFlow v9 collector
auth_api: true
host_network: true
options:
  log_level: info
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  leave_front_door_open: false
  ntop_auth: false
  zmq_loc_port: 5556
  ntopng_loc_port: 3000
  netflow2ng_loc_port: 8080
  redis_loc_port: 6379
  custom_scripts: false
  dns_mode: 0
  local_net:
    - 192.168.1.0/24
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool
  ntop_auth: bool
  zmq_loc_port: int(1024,65535)
  ntopng_loc_port: int(1024,65535)
  netflow2ng_loc_port: int(1024,65535)
  redis_loc_port: int(1024,65535)
  custom_scripts: bool
  dns_mode: match(^[0-4]$)
  local_net:
    - match(^(?:[0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}(\=[A-Z0-9_]+)?$)
  export_flows: "str?"
  geoip_account_id: "int?"
  geoip_license_key: "str?"
